//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPhoneShop.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceipt
    {
        public int ProductID { get; set; }
        public int ShipmentID { get; set; }
        public double Price { get; set; }
        public Nullable<double> Promotion { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
        public System.DateTime DateReceipt { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
